# Site settings
name: Jesse Chumo
title: ğŸ‘¨ğŸ¾â€ğŸ’» Jesse Chumo | Software Engineer
description: Software Engineer skilled in full-stack development, CI/CD, secure authentication, and machine learning. Passionate about building high-quality software in fast-paced startup environments.
url: https://jessechumo.com/
baseurl: ''
email: jessechumo@gmail.com
cover: https://jessechumo.com/img/og.png
logo: https://jessechumo.com/img/emojis/technologist.png
resume: jessechumo - resume.pdf
social:
  - title: email
    url: mailto:jessechumo@gmail.com
  - title: github
    url: https://github.com/jessechumo
  - title: linkedin
    url: https://www.linkedin.com/in/jessechumo
  - title: twitter
    url: https://twitter.com/jessechumo

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
